non_prod_env_crn = "crn://confluent.cloud/organization=ebfa2bb8-8dfa-4d73-a075-9da6b5c3a3b5/environment=env-rvw7k/cloud-cluster=lkc-1j1r83"
env_name = "niyi"
purpose = "Non Prod Cluster"
cluster_name = "non-prod"
ksql_cluster = "ksql-non-prod"
ksql_app_id = "ksql-non-prod"
owner_email = "nodumosu+svcs-ne@confluent.com"
region = "us-east-1"
resource_name = "niyi"
