name: "Terraform Plan"

on:
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for the terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Add CCloud Creds
        run: |
          export TF_VAR_confluent_api_key=${{ secrets.CONFLUENT_CLOUD_API_KEY }}
          export TF_VAR_confluent_api_secret=${{ secrets.CONFLUENT_CLOUD_API_SECRET }}

      - name: terraform init & plan
        run: |
          cd non-prod
          echo "confluent_api_key = ${{ secrets.CONFLUENT_CLOUD_API_KEY }}" >> non-prod.tfvars
          echo "confluent_api_secret = ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}" >> non-prod.tfvars
          echo "\n" >> non-prod.tfvars
          cat non-prod.tfvars
          terraform init
          terraform plan -var-file=non-prod.tfvars

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: non-prod
          var_file: non-prod.tfvars